### ISSUE TITLE
Script for visualize SELDnet results

### ISSUE THREAD

**Issue by ennioO** [Qinstudy/hello-world#2]
Hi @Qinstudy ! Sorry for contact you here. I'm working on Adavanne's SELDnet for a small university project, and I need to visualize the results. From the issues in that repository I know you probably did a script for that. If you have it, can you send me it in some way?

**Comment by Qinstudy** [comment]
Hello，@ennioO，this script comes from seld-dcase2019, you can view it from this link. If you have some problems,we can discuss together in order to study SELD. 
https://github.com/sharathadavanne/seld-dcase2019/blob/master/misc_files/visualize_SELD_output.py

**Comment by ennioO** [comment]
Thanks for your answer. I've already seen this script, and I've tried to modify SELDnet scripts in order to dump results and visualize them with it. But I am not able to do this. Additionally this script plots only azimuth and elevation results, while a I'm interested in visualizing also xyz results. Unfortunately I'm very poor in python.

**Comment by Qinstudy** [comment]
I know your meaning. You want to visiual xyz results.Can you have xyz results?

**Comment by ennioO** [comment]
Yes, I have either azi-ele and xyz results. The problem is that dcase script you linked me plots the results after they have been dumped in any directory, but I am not able to modify SELDnet scripts (https://github.com/sharathadavanne/seld-net) for dumping results.
